apiVersion: v1
data:
  application.namespaces: ""
  applicationsetcontroller.enable.leader.election: "false"
  applicationsetcontroller.enable.progressive.syncs: "false"
  applicationsetcontroller.log.format: text
  applicationsetcontroller.log.level: info
  applicationsetcontroller.namespaces: ""
  applicationsetcontroller.policy: sync
  controller.ignore.normalizer.jq.timeout: 1s
  controller.log.format: text
  controller.log.level: info
  controller.operation.processors: "10"
  controller.repo.server.timeout.seconds: "60"
  controller.self.heal.timeout.seconds: "5"
  controller.status.processors: "20"
  controller.sync.timeout.seconds: "0"
  dexserver.log.format: text
  dexserver.log.level: info
  hydrator.enabled: "false"
  notificationscontroller.log.format: text
  notificationscontroller.log.level: info
  otlp.address: ""
  redis.server: argo-cd-argocd-redis:6379
  repo.server: argo-cd-argocd-repo-server:8081
  reposerver.log.format: text
  reposerver.log.level: info
  reposerver.parallelism.limit: "0"
  server.basehref: /
  server.disable.auth: "false"
  server.enable.gzip: "true"
  server.enable.proxy.extension: "true"
  server.insecure: "false"
  server.log.format: text
  server.log.level: info
  server.repo.server.strict.tls: "false"
  server.rootpath: ""
  server.staticassets: /shared/app
  server.x.frame.options: sameorigin
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: argo-cd:/ConfigMap:argocd/argocd-cmd-params-cm
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"application.namespaces":"","applicationsetcontroller.enable.leader.election":"false","applicationsetcontroller.enable.progressive.syncs":"false","applicationsetcontroller.log.format":"text","applicationsetcontroller.log.level":"info","applicationsetcontroller.namespaces":"","applicationsetcontroller.policy":"sync","controller.ignore.normalizer.jq.timeout":"1s","controller.log.format":"text","controller.log.level":"info","controller.operation.processors":"10","controller.repo.server.timeout.seconds":"60","controller.self.heal.timeout.seconds":"5","controller.status.processors":"20","controller.sync.timeout.seconds":"0","dexserver.log.format":"text","dexserver.log.level":"info","hydrator.enabled":"false","notificationscontroller.log.format":"text","notificationscontroller.log.level":"info","otlp.address":"","redis.server":"argo-cd-argocd-redis:6379","repo.server":"argo-cd-argocd-repo-server:8081","reposerver.log.format":"text","reposerver.log.level":"info","reposerver.parallelism.limit":"0","server.basehref":"/","server.disable.auth":"false","server.enable.gzip":"true","server.enable.proxy.extension":"true","server.insecure":"false","server.log.format":"text","server.log.level":"info","server.repo.server.strict.tls":"false","server.rootpath":"","server.staticassets":"/shared/app","server.x.frame.options":"sameorigin"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-cd:/ConfigMap:argocd/argocd-cmd-params-cm"},"name":"argocd-cmd-params-cm","namespace":"argocd"}}
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2025-05-03T20:22:17Z"
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "11504559"
  uid: 9fd8c8cd-17a3-455c-983e-45147d192d32
