apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  scopes: '[read:user, user:email, read:org]'
  policy.default: role:no-access
  policy.csv: |-
    p, role:readonly, extensions, invoke, metrics, allow
    g, patrick, role:admin
    g, patrickeschenbach96@gmail.com, role:admin
