apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  admin.password: JDJhJDEyJE9uWVRIOC90WndFOUNnU0FwL2ltU3UuMnY5UmRIMVFnSDN5NFFTbXJzRGJmLlQ2US4zQWxP 
  dex.github.clientID: IE92MjNsaTJPN3FkRzN3d2pwNVZI
  dex.github.clientSecret: NDU0MzZmYzIzYzdkOTg5MWUwZGI0NDc2NDdhNGEzNzBiMGEyNjNhOA==
